### ISSUE TITLE
Database with views not rendering correctly

### ISSUE THREAD

**Issue by biswadipmaity** [NotionX/react-notion-x#242]
Hi Devs,
I am trying to render this notion page: [[Public Notion URL]](https://biswadip.notion.site/4925f1b6acbf499b9486148e2be2c5d7?v=94cf7bdf2deb409b9c6662599fd0ab76).
The rendered site with react-notion-x is  [[ here ]](https://iot.biswadip.com/course-schedule) using the nextjs-notion-starter-kit.

As you can see, the 1. views are missing completely, 2. The header text is messed up (I am using next build and next start for prod use), and 3. there are some stray images on the bottom. 

Can anyone please guide me to what is the cause of this issue ? 

Thanks in advance!

**Comment by transitive-bullshit** [comment]
1. Are you using `showCollectionViewDropdown={false}`? (which is the default in the starter kit)
2. Seems like a bug
3. Seems like a bug

I'm looking into 2 and 3 today. Thanks!

**Comment by transitive-bullshit** [comment]
2 and 3 should be fixed if you rebase / merge the latest changes from the starter kit. note that i'm not sure what's going on the the table header, but the table columns should display properly now.

if you include these fixes, let me know how things look.

**Comment by biswadipmaity** [comment]
Hi Travis,
Thank you so much for your quick help! Indeed, `showCollectionViewDropdown` was `false` and 2/3 are resolved now. I have updated the rendered site to reflect the same. 

Regarding 1, when I set `showCollectionViewDropdown={true}`, while the views show up awkwardly, I still cannot click on them. Here is a screenshot:
![image](https://user-images.githubusercontent.com/12016122/160291017-eaca44e9-bbbe-48c2-9d1d-ea15cacc1370.png)
By any chance can you help me with what is wrong?

thanks again!

**Comment by transitive-bullshit** [comment]
Ahhh you need uncomment this line: https://github.com/transitive-bullshit/nextjs-notion-starter-kit/blob/main/pages/_app.tsx#L15

I'll make this the default going forwards so nobody else gets tripped up.

**Comment by biswadipmaity** [comment]
That did solve the alignment issues as well as the clicks on the page !! Thanks a lot..

One last question: On [[ this notion page ]](https://biswadip.notion.site/Assignments-83b3e073eb0648ec8fbd63f5fa74e7c2), I have a view of the database that is not rendering correctly now. Is this supported ?

**Comment by normdoow** [comment]
Looks like Notion's latest change to databases has messed up our notion-client query of the data.
This was the change where Notion made all the different views be more explicit.
Also seeing that cover image data isn't coming through for Gallery Views when they are in groups. On this page for example.
56a9316880be423ab7137d3784a3a26f

**Comment by transitive-bullshit** [comment]
I did some preliminary investigation in #246

**Comment by transitive-bullshit** [comment]
Tracking this in #260
